---
version: '3.1'

services:

  auth:
    image: ku/sund/smartsleep/auth:latest
    build:
      context: ./auth
    environment:
      - NODE_ENV=production
      - CONFIG_ENV=production
    networks:
      - production
  
  activity:
    image: ku/sund/smartsleep/activity:latest
    build:
      context: ./activity
    networks:
      - production
    secrets:
      - source: activitydb
        target: database.properties

  survey:
    image: limesurvey:latest
    build:
      context: ./limesurvey
    ports:
      - "8081:80"
    networks:
      - production
    secrets:
      - source: limeconfig
        target: config.php

  notify:
    image: ku/sund/smartsleep/notify:latest
    build:
      context: ./notify
    networks:
      - production
    secrets:
      - source: fbadminsdk
        target: firebase-adminsdk.json
      - source: activitydb
        target: database.properties

  proxy:
    image: ku/sund/smartsleep/proxy:latest
    build:
      context: ./proxy
    depends_on:
      - auth
      - activity
      - survey
    ports:
      - "8080:8080"
    networks:
      - production


networks:
  production:

secrets:
  activitydb:
    file: ./activity/secrets/database-production.properties
  fbadminsdk:
    file: ./secrets/firebase-adminsdk.json
  limeconfig:
    file: ./secrets/config-production.php

